---
title: NAAKTSLAK!
hero_image: images/banner.png
description: Speel het klassieke spel Snake na op je Sense HAT
theme: violet #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: games
technologies: sense-hat, electronic-components, python
site_areas: projects
hardware: sense-hat, electronic-components
software: python
version: 4.0.1
last_tested: 2017-10-01
steps:
  - title: Inleiding
  - title: Wat heb je nodig
  - title: Maak verbinding met de Sense HAT
  - title: Teken de naaktslak
  - title: Verplaats de slak
  - title: Gebruik de joystick
  - title: Maak groenten
  - title: Groenten eten
  - title: Groeien en versnellen
  - title: Game over
  - title: "Uitdaging: gekke groenten"
