title: slug
hero_image: images/banner.png
description: slug description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "animals, jokes/pranks, space, photography, music/sound, physical computing, games, robots, geography"
technologies: "electronics, sense-hat, physical computing, html/css, scratch, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
